@baseUrl = http://localhost:3000/api

# @name getAllCart
GET {{baseUrl}}/permissions


####


# @name addNewCart
POST http://localhost:3000/api/permissions
Content-Type: application/json

{
   
    "name": "User",
      "permissions": [
        {
          "CLIENT_MANAGEMENT": {
            "create": true,
            "update": false,
            "view": true,
            "delete": true
          }
        },
        {
          "SCHEDULE_MANAGEMENT": {
            "create": true,
            "update": false,
            "view": true,
            "delete": true
          }
        },
        {
          "LOCATION_MANAGEMENT": {
            "create": true,
            "update": false,
            "view": true,
            "delete": true
          }
        },
        {
          "SETTINGS": {
            "create": true,
            "update": false,
            "view": true,
            "delete": true
          }
        }
      ]
  }

###
# @name updateCart
PATCH http://localhost:3000/api/permissions/RDX0kIT
Content-Type: application/json

{
    "name": "User Test",
    "permissions": [
      {
        "CLIENT_MANAGEMENT": {
          "create": true,
          "update": false,
          "view": true,
          "delete": true
        }
      },
      {
        "SCHEDULE_MANAGEMENT": {
          "create": true,
          "update": false,
          "view": true,
          "delete": true
        }
      },
      {
        "LOCATION_MANAGEMENT": {
          "create": true,
          "update": false,
          "view": true,
          "delete": true
        }
      },
      {
        "SETTINGS": {
          "create": true,
          "update": false,
          "view": true,
          "delete": true
        }
      }
    ],
    "id": "RDX0kIT"
  }


###
# @name deleteCart
DELETE http://localhost:3000/api/cart/localhost:3000/api/cart/hoanganh141000tb@gmail.com